sudo: false
language: php
php:
  - 5.5
  - 5.6
#  - 7.0
#matrix:
#  allow_failures:
#    - php: 7.0
#env:
#  matrix:
#    - MAGENTO_VERSION=magento-mirror-1.9.2.4
#    - MAGENTO_VERSION=magento-mirror-1.9.1.1
#    - MAGENTO_VERSION=magento-mirror-1.9.0.1
#    - MAGENTO_VERSION=magento-mirror-1.8.1.0
branches:
  except:
    - /^v?(\d+\.)+\d+$/
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
script:
  # Basic Linting
  - bash -n ./scheduler_cron.sh
  - find . -iname *.php -print0 | xargs -0 -n1 php -l
  - find . -iname *.phtml -print0 | xargs -0 -n1 php -l
  # Code Style
  - php phpcs.phar --standard=./phpcs.xml --encoding=utf-8 --report-width=180 --colors -d display_errors=1 ./app
  # Unit Tests
#  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - travis@fabrizio-branca.de
      - lee.saferite@aoe.com
    on_success: always
    on_failure: always
